# This is a basic workflow to help you get started with Actions

name: HEXO

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: use nodejs
      uses: actions/setup-node@v2-beta
      with: 
        node-version: '12'
    - name: install hexo
      run: npm install hexo-cli -g
      
    - name: install package
      run: |
        npm install
        npm install hexo-deployer-git --save
        
    - name: hexo clean&generate
      run: |
        hexo clean
        hexo generate
        
    - name: config git
      run: |
        git config user.name "hoxucool"
        git config user.email "hoxucool@foxmail.com"
        git config --global user.name "hoxucool"
        git config --global user.email "hoxucool@foxmail.com"
        
    - name: deploy
      run: |
        git config user.name "hoxucool"
        git config user.email "hoxucool@foxmail.com"
        sed -i "s/gh_token/${{ secrets.GH_TOKEN }}/g" ./_config.yml
        hexo deploy
